name: Build & Deploy Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build web release
        run: flutter build web --release

      - name: Prepare docs folder
        run: |
          rm -rf docs
          cp -R build/web docs
          # Ensure your custom domain is preserved:
          echo "www.madlabzdevs.net" > docs/CNAME

      - name: Commit and push docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "ci: rebuild website" || echo "No changes to commit"
          git push